In [4]:
from numpy import *

In [5]:
a = array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(a.shape) # shape : It is used find the dimensional shape of the array

(2, 4)


In [7]:
#ndim : returns an integer that tells us how many dimensions the array have.
print("ndim",a.ndim)

ndim 2


In [8]:
#size : return the size of the array
print("Size : ",a.size)

Size :  8


In [9]:
#dtype : return the datatype of the array
print("datatype : ",a.dtype)

datatype :  int64


In [10]:
#itemsize : The element size of this data-type object
print(a.itemsize)

8


In [11]:
print(a.data)

In [12]:
m1 = array([[1,2],[3,4]])
m2 = array([[5,6],[7,8]])
print(m1)
print(m2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [13]:
#dot : return the multiplication of the matrix
mul = dot(m1,m2)
print(mul)

[[19 22]
 [43 50]]


In [14]:
#multiply : it only multiply the elements
mult = multiply(m1,m2) #only multiplication
print(mult)

[[ 5 12]
 [21 32]]


In [15]:
#subtract : will subtract the matrix
subtrac = subtract(m2,m1)
print(subtrac)

[[4 4]
 [4 4]]


In [16]:
#add : will add the two or more matrix
addM = add(m1,m2)
print(addM)

[[ 6  8]
 [10 12]]


In [17]:
b = array([4,5,56,7,8,9,12,45])
print(b[2:])  #starting from the 2nd element to the end

[56  7  8  9 12 45]


In [18]:
#starting from first element to the 2-1 element
print(b[:2])

[4 5]


In [19]:
#starting from the 2nd element to the 4th element
print(b[2:5])

[56  7  8]


In [20]:
#in the 1st matrix of m1 2 elements
print(m1[1:2])

[[3 4]]


In [21]:
#sum of all the elements in the array
print(b.sum())

146


In [22]:
c = array([1,2,3,4,5,6,7,8,9])
#reshape : shape the array according to our choice
print(c.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#max = maximum element from the array
print(c.max())


9


In [25]:
#min : minimum element from the array
print(c.min())

1


In [26]:
#axis=1 means row wise maximum
re = c.reshape(3,3)
print("Max in row is : ",re.max(axis=1))

Max in row is :  [3 6 9]


In [27]:
#axis=0 means column wise minimum
print("Min in row is : ",re.min(axis=0))

Min in row is :  [1 2 3]


In [28]:
m4 = array([4,9,25])
#sqrt : square root of the elements
print(sqrt(m4))

[2. 3. 5.]


In [30]:
#std : calculates the standard deviation of given data along a specified axis.
print("Standard deviation : ",std(m4))

Standard deviation :  8.9566858950296


In [31]:
#vstack : arrange the array vertically
print(vstack((m1,m2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
#hstack : arrange the array horizontally
print(hstack((m1,m2)))

[[1 2 5 6]
 [3 4 7 8]]


In [33]:
#arange : starting to 0 to 20 range with 2 gap
print(arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [34]:
#in float value
print(arange(0,20,2,float))

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [35]:
#same as arange but default in float
print(linspace(0,20,5))

[ 0.  5. 10. 15. 20.]


In [36]:
a = array([1,2,3,4,5,6,7,8])
hnew = hsplit(a,2)
print(hnew)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [39]:
m1=array([[1,2],[3,4]])
m2=array([[5,6],[7,8]])
v=vstack((m1,m2)) # arrange array vertically
print(v)
h=hstack((m1,m2)) # horizontally
print(h)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [40]:
ht=h.T # swap the indices of row and column if its row then it swap to column
print(ht)

[[1 3]
 [2 4]
 [5 7]
 [6 8]]


In [41]:
for i in nditer(ht):
    print(i)

1
2
5
6
3
4
7
8


In [42]:
arr=array([23,34,45,67])
print("exp :",exp(arr)) # return the exponential of each element

exp : [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]


In [46]:
arr=array([23,34,45,67])
print("sin : ",sin(arr)) #returns the sin of each element
print("cos : ",cos(arr)) #returns the cosine of each element
print("Log : ",log(arr)) # retuns the logaritham of each element

sin :  [-0.8462204   0.52908269  0.85090352 -0.85551998]
cos :  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log :  [3.13549422 3.52636052 3.80666249 4.20469262]


In [48]:
from scipy import stats as st

In [ ]:
print("mean : ",mean)